MVC.Sorveteria/Models/Loja.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Sorveteria.Models
{
    public class Loja
    {
        public int LojaId { get; set; }
        public string Nome { get; set; }
        public string Local { get; set; }

        //Relacionamento
        public IList<Sorvete> Sorvetes { get; set; }
    }
}

MVC.Sorveteria/Models/Sorvete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Sorveteria.Models
{
    public class Sorvete
    {
        public int SorveteId { get; set; }
        public string Nome { get; set; }
        public string Sabor { get; set; }
        public DateTime DataValidade { get; set; }
        public bool Casquinha { get; set; }

        //Relacionamento
        public Loja Loja { get; set; }
        public int LojaId { get; set; }
    }
}

MVC.Sorveteria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Sorveteria.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC.Sorveteria/Controllers/SorveteController.cs
using MVC.Sorveteria.Models;
using MVC.Sorveteria.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Sorveteria.Controllers
{
    public class SorveteController : Controller
    {
        private UnityOfWork _unit = new UnityOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Sorvete sorvete)
        {
            _unit.SorveteRepository.Cadastrar(sorvete);
            _unit.Salvar();
            TempData["msg"] = "Sorvete cadastrado!";
            return RedirectToAction("Cadastrar");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVC.Sorveteria/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home</h2>

MVC.Sorveteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("SORVETE", "Cadastrar", "Sorvete", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("LOJA", "Cadastrar", "Loja", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MVC.Sorveteria/Views/Sorvete/Cadastrar.cshtml
@model MVC.Sorveteria.Models.Sorvete
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar um sorvete</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(s => s.Nome)
        @Html.TextBoxFor(s => s.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.Sabor)
        @Html.TextBoxFor(s => s.Sabor, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.DataValidade)
        @Html.TextBoxFor(s => s.DataValidade, new { @class = "form-control" })
    </div>
    <div class="form-check">
        @Html.Label("Casquinha ?")
        @Html.CheckBoxFor(s => s.Casquinha, new { @class = "form-check-input" })
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}